### ISSUE TITLE
Need unique key prop somewhere in Select component

### ISSUE THREAD

**Issue by jaschaephraim** [expandorg/expand-components#3]

**Comment by kieranoreilly** [comment]
I believe the unique key on the current version is "value".

@sslava I propose the unique key should be "id"
There could be a situation where 2 options in select have the same value. For instance, in a sentiment analysis study you could say "What is your mood when you read this tweet" and choices be "Excited, depressed, happy, sad" The study might only care about boolean answers and make the values, "happy, sad, happy, sad". However, there shouldn't be a situation where they have the same id. Was the switch because "id" is optional?

**Comment by sslava** [comment]
solved
